{% set version = "1.1.1" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-cyclocomp
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cyclocomp_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cyclocomp/cyclocomp_{{ version }}.tar.gz
  sha256: 9aff06d58bb060e23ac64337a95aebb2c69371b9de5f2549626e3e66acb5b14d

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-callr
    - r-crayon
    - r-desc
    - r-remotes
    - r-withr
  run:
    - r-base
    - r-callr
    - r-crayon
    - r-desc
    - r-remotes
    - r-withr

test:
  commands:
    - $R -e "library('cyclocomp')"           # [not win]
    - "\"%R%\" -e \"library('cyclocomp')\""  # [win]

about:
  home: https://github.com/MangoTheCat/cyclocomp
  license: MIT
  summary: Cyclomatic complexity is a software metric (measurement), used to indicate the complexity of a program. It is a quantitative measure of the number of linearly independent paths through a program's source code. It was developed by Thomas J. McCabe, Sr. in 1976.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
