travis:
  secure:
    BINSTAR_TOKEN: 5TTTwG8rhUmL/+vBO9973ogC1qfOLh0a5U33UO+teGilnXlZ+VT727Nv/k4+poWdsjKMH95DZpH4D+lzj4lxhj1K7u2JTiKNvVkvnmwW2tpvuKsvQ4Dp3MdnKF5uUOK2V+BElhbXCFw9OGzMCOX8eIq2wnCeb4zGpY3NeBOVpOt70Qh4tMPN+zdPWZ1RYZXDEGlG2n2RjHmwYoIiKaZwEJc8WcOqP2ETvL54griBnvSzZ3aIEOpsVmxW1b2zSp/ba4lwlT+PGcXYBSsTtQ8y9v7tdc4BLyqJa02klPlfTGtEB6i4EoOR3j2hSUxOv0u2MqYHuIQUFge4l7drO8RubVUn4tDJ1Q7Ons/SARXV9M7cw7NR/pjb/g5yzvWpH673snfSa26edtxxuL4WZoNupisjuJ2OLYC4NMol1p5edaaZa7CWal7BKTvB4UizikoRaMhriE+zox7c9ok0FMKsj7MtKqAniWUszViqPyoXAeTXedaBgEJsvN4mkFbhiwtn5RLcZzaYCl9+NB/s+Ixc98k6ur0Ivb3Jj3RborQTrhl7vzDtOiiKqCq6jkA5FxBkbq2R4SvP6i6zThVw8pNgcT7usSTEKZQDkmo72l1l1UWwD3spVj7hKiW1wt9RD92v5RXDFNPYLIaTjl7UacPAC3LDBT3aeJyqu2mFqVD48Bo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
